### ISSUE TITLE
Not able to create `britive_profile_policy` with the latest version `>= 2.0`

### ISSUE THREAD

**Issue by RaghavK12RK** [britive/terraform-provider-britive#20]
Hi, could anyone help me out in getting the issue resolved, As i have used the latest britive version in creating the `britive_profile_policy` as it states in the document as well as i was creating this for the replacement of `britive_profile_tag`.

The plan is successful but while applying it is not getting created.

Need your help and thanks for the earlier support if i get on this!!!

![image](https://user-images.githubusercontent.com/109405973/219652366-57e7fbbc-a867-4c01-b795-949db1119cae.png)

**Comment by RaghavK12RK** [comment]
Can anyone address this issue

**Comment by mpatnode** [comment]
Hi @RaghavK12RK sorry for the slow response.  Just found this now.   Will have someone investigate.

**Comment by RaghavK12RK** [comment]
Hi @mpatnode Any update on this issue?

**Comment by mpatnode** [comment]
The problem appears to be your tenant is still using v1 profiles which does not support this feature.   It my understanding that your team is working closely with Britive support to upgrade the tenant to v2, but I don't have any details on when that effort will be completed.
